# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
# Default to bash
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Git config
        run : |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: build
        run: deno run -A main.ts
      - name : Push
        run : deno run -A push.ts
  
